name: pipeline
on:
- push

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: make
        version: 1.0
    - uses: docker/setup-buildx-action@v3
    - name: Build the Data Platform
      run: make build
    - run: docker images
    - name: Export the Docker image
      run: |
        mkdir -p "./docker-images/jump"
        docker save --output="./docker-images/jump/data-platform.tar" "jump/data-platform:latest"
    - uses: actions/upload-artifact@v4
      with:
        name: docker-images
        path: "./docker-images"
        retention-days: 2
  
  refresh:
    needs:
    - build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: make
        version: 1.0
    - uses: docker/setup-buildx-action@v3
    - uses: actions/download-artifact@v4
      with:
        name: docker-images
        path: "./docker-images"
    - name: Import the Docker image
      run: docker load --input "./docker-images/jump/data-platform.tar"
    - name: Refresh the Data Platform
      run: make refresh
    - run: find "."
    - uses: actions/upload-artifact@v4
      with:
        name: exports
        path: "./data/exports"
        retention-days: 2

