name: pipeline
on:
- push

jobs:
  pipeline:
    runs-on: ubuntu
    steps:
    - uses: actions/checkout@v4
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: make
        version: 1.0
    - uses: docker/setup-buildx-action@v3
    - run: make
